version: 2

registries:
  bb-artifactory:
    type: maven-repository
    url: https://repo.backbase.com
    username: ${{secrets.ARTIFACTORY_USERNAME}}
    password: ${{secrets.ARTIFACTORY_PASSWORD}}

updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "gitleaks/gitleaks-action"
        versions: ["2.x"]

  # Maintain dependencies for docker
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly

  # Maintain dependencies for maven
  - package-ecosystem: maven
    directory: "/"
    registries:
      - bb-artifactory
    schedule:
      interval: weekly