repository:
  name: amazon-ses-connector
  description: "This service is used by the Message Delivery capability, and provides integration to Amazon SES for sending emails."
  homepage: https://github.com/Backbase/amazon-ses-connector
  topics: backbase, message-delivery, communication, amazon, third-party