openapi: 3.0.3
info:
  title: Actions SMS integration
  description: Send an SMS message about a business event to a bank user.
  version: 2.0.6
  x-icon: settings
  license:
    name: Copyright Backbase
    url: 'https://www.backbase.com/legal'
servers:
  - description: Prism mock server
    url: 'http://localhost:4010'
tags:
  - name: sms integration spec
paths:
  /service-api/v2/sms:
    summary: SMS
    description: Send SMS
    post:
      tags:
        - sms
      summary: Endpoint for sending sms message.
      description: Endpoint for sending sms message
      operationId: postSMS
      requestBody:
        description: Endpoint for sending sms message
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SMSPostRequestBody'
            example:
              $ref: '#/components/examples/SMSPostRequestBody'
      responses:
        '201':
          description: |
            # SMS response

            Returns true if there were no exceptions during sending SMS
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SMSPostResponseBody'
              example:
                $ref: '#/components/examples/SMSPostResponseBody'
        '400':
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
              example:
                $ref: '#/components/examples/BadRequestError'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
              example:
                $ref: '#/components/examples/ForbiddenError'
        '500':
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
              example:
                $ref: '#/components/examples/InternalServerError'
components:
  schemas:
    SMSPostRequestBody:
      required:
        - message
        - to
      type: object
      properties:
        to:
          type: array
          description: List of phone numbers to which SMS message should be sent
          items:
            maxLength: 36
            minLength: 1
            type: string
        from:
          maxLength: 36
          type: string
          description: Phone number of SMS sender. Note that setting this field could lead to unexpected behaviour(for example - implementation service has no access to this phone number)
        message:
          maxLength: 256
          minLength: 1
          type: string
          description: SMS message body
        additions:
          description: Additional properties
          type: object
          additionalProperties:
            type: string
    SMSPostResponseBody:
      title: SMS Request
      type: object
      properties:
        sent:
          type: boolean
        additions:
          description: Additional properties
          type: object
          additionalProperties:
            type: string
      example:
        sent: true
    ErrorItem:
      title: ErrorItem
      type: object
      properties:
        message:
          description: Any further information.
          type: string
        key:
          description: '{capability-name}.api.{api-key-name}. For generated validation errors this is the path in the document the error resolves to. e.g. object name + ''.'' + field'
          type: string
        context:
          description: Context can be anything used to construct localised messages.
          type: object
          additionalProperties:
            type: string
    ForbiddenError:
      title: ForbiddenError
      type: object
      properties:
        message:
          description: Any further information
          type: string
        errors:
          description: Detailed error information
          type: array
          items:
            $ref: '#/components/schemas/ErrorItem'
    BadRequestError:
      title: BadRequestError
      type: object
      properties:
        message:
          description: Any further information
          type: string
        errors:
          description: Detailed error information
          type: array
          items:
            $ref: '#/components/schemas/ErrorItem'
      required:
        - message
    InternalServerError:
      title: InternalServerError
      type: object
      description: Represents HTTP 500 Internal Server Error
      properties:
        message:
          description: Further Information
          type: string
  examples:
    SMSPostRequestBody:
      value:
        to:
          - '+1652304812'
          - '+380961281282'
        from: '+123456789'
        message: 'Dear client! Your balance is: 2450 EUR'
    SMSPostResponseBody:
      value:
        sent: true
    ForbiddenError:
      value:
        message: Access to requested resource denied.
        errors:
          - message: 'Resource access denied due to an insufficient user quota of {quota}.'
            key: common.api.quota
            context:
              quota: someQuota
    BadRequestError:
      value:
        message: Bad Request
        errors:
          - message: 'Value Exceeded. Must be between {min} and {max}.'
            key: common.api.shoesize
            context:
              max: '50'
              min: '1'
    InternalServerError:
      value:
        message: Description of error
