releases:
  - name: backbase-env
    chart: internal/backbase-env
    version: 0.16.3
    labels:
      tier: infrastructure
      component: env
    values:
      - ../../values/backbase-env.yaml
      - ../../values/database/mysql/env-values.yaml

  - name: ips-registry
    chart: backbase-charts/backbase-app
    version: 0.23.13
    labels:
      tier: ips
      component: registry
    values:
      - ../../values/global.yaml
      - ../../values/ips/registry.yaml
    set:
      - name: global.ips-registryVersion
        value: {{ env "IPS_REGISTRY_VERSION" | default "custom-m1-b1" | quote }}

  - name: ips-edge
    chart: backbase-charts/backbase-app
    version: 0.23.13
    labels:
      tier: ips
      component: edge
    values:
      - ../../values/global.yaml
      - ../../values/ips/edge.yaml
    set:
      - name: global.ips-edgeVersion
        value: {{ env "IPS_EDGE_VERSION" | default "2022.05" | quote }}

  - name: ips-authentication-dev
    chart: backbase-charts/backbase-app
    version: 0.23.13
    labels:
      tier: ips
      component: auth
    values:
      - ../../values/global.yaml
      - ../../values/ips/auth.yaml
      - env:
          BACKBASE_ENVROLE: editorial
    set:
      - name: global.ips-authVersion
        value: {{ env "IPS_AUTH_VERSION" | default "2022.03-no-production" | quote }}

  - name: ips-bas-token-converter
    chart: backbase-charts/backbase-app
    version: 0.23.13
    labels:
      tier: ips
      component: token-converter
    values:
      - ../../values/global.yaml
      - ../../values/ips/token-converter.yaml
    set:
      - name: global.ips-tcVersion
        value: {{ env "IPS_TC_VERSION" | default "2022.05" | quote }}

  - name: communication
    chart: backbase-charts/backbase-app
    version: 0.23.13
    labels:
      tier: cxs
      component: communication
    values:
      - ../../values/global.yamlÏ
      - ../../values/database/mysql/app-values.yaml
      - ../../values/communication-m10y.yaml
    set:
      - name: global.communication-version
        value: {{ env "COMMUNICATION_IMAGE_VERSION" | default "release" | quote }}
      - name: eureka.instance.non-secure-port
        value: {{ env "COMMUNICATION_PORT" | default "8080" | quote }}
      - name: app.image.repository
        value: {{ env "COMMUNICATION_IMAGE_REPOSITORY" | default "communication" | quote }}

  - name: channel-mock
    chart: backbase-charts/backbase-app
    version: 0.23.13
    labels:
      tier: cxs
      component: communication
    values:
      - ../../values/global.yaml
      - ../../values/channel-mock-m10y.yaml
    set:
      - name: global.communication-version
        value: {{ env "COMMUNICATION_IMAGE_VERSION" | default "release" | quote }}
      - name: eureka.instance.non-secure-port
        value: {{ env "COMMUNICATION_PORT" | default "8080" | quote }}
      - name: app.image.repository
        value: {{ env "SYSTEM_TEST_MOCK_CHANNEL_IMAGE_REPOSITORY" | default "communication-system-tests-channel-mock" | quote }}

  - name: system-tests-communication
    chart: ../../chart/system-tests
    labels:
      tier: system-tests
      component: communication-system-tests
    set:
      - name: communication.port
        value: {{ env "COMMUNICATION_PORT" | default "8080" | quote }}
      - name: image.tag
        value: {{ env "SYSTEM_TEST_IMAGE_VERSION" | default "release" | quote }}
      - name: args
        value: "multi-tenancy"
