name: "Build and publish artifact"
description: "Github composite action to tag version on Github and then Build and publish artifact to ECR/ACR"
##
#
# Action responsible for setting AWS credentials,
# tagging the version on Github,
# building docker image and pushing to ECR/ACR
#
##
inputs:
  token:
    description: "Github Token"
    required: true
  accessKey:
    description: "AWS access key id"
    required: true
  secretAccessKey:
    description: "AWS secret access key"
    required: true
  region:
    description: "AWS region"
    required: true
  azure-creds:
    description: "Azure creds"
    required: true
  azure-base-url:
    description: "Azure base-url"
    required: true
  awsEnabled:
    description: "aws enabled or not"
    required: false
    default: 'false'
  azureEnabled:
    description: "azure enabled or not"
    required: false
    default: 'false'
  enableBuildTagging:
    description: "Enable build tagging"
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:

    ##
    #
    # Configure AWS credentials
    #
    ##
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.accessKey }}
        aws-secret-access-key: ${{ inputs.secretAccessKey }}
        aws-region: ${{ inputs.region }}

    ##
    #
    # Setting AWS login details in env variables
    #
    ##
    - name: Get AWS ECR credentials
      id: ecr-credentials
      shell: bash
      run: |
        echo "::set-output name=username::AWS"
        echo "::set-output name=password::`aws ecr get-login-password --region ${{ inputs.region }}`"

    ##
    #
    # Extract build version for tagging
    #
    ##
    - name: Extract build version for tagging
      id: build-version
      uses: ./.github/actions/extract-version
      with:
        token: ${{ inputs.token }}

    ##
    #
    # Push tag with build version on Github
    #
    ##
    - name: Add tag
      shell: bash
      run: |
        if [[ "${{inputs.enableBuildTagging}}" == "true" ]]; then
          echo "Adding github tag ${{ steps.build-version.outputs.build-version }}"
          git tag -a ${{ steps.build-version.outputs.build-version }} -m "${{ steps.build-version.outputs.build-version }}"
          git push origin ${{ steps.build-version.outputs.build-version }}
        fi

    ##
    #
    # Use ssdk's maven docker-image profile to build and push image to ECR
    #
    ##
    - name: Build docker image to ECR
      shell: bash
      run: |
        if [[ "${{inputs.awsEnabled}}" == "true" ]]; then
          echo "ECR Docker build with tag ${{ steps.build-version.outputs.build-version }}"
          mvn clean package -Pdocker-image -Pno-scs -Dmaven.test.skip -Djib.to.tags=${{ steps.build-version.outputs.build-version }} -Djib.to.auth.username=${{ steps.ecr-credentials.outputs.username }}  -Djib.to.auth.password=${{ steps.ecr-credentials.outputs.password }} -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
        fi

    ##
    #
    # azure login
    #
    ##
    - name: 'Az CLI login'
      uses: azure/login@1f63701bf3e6892515f1b7ce2d2bf1708b46beaf #v1.4.3
      with:
        creds: ${{ inputs.azure-creds }}
        base-url: ${{ inputs.azure-base-url }}

    - name: 'Run az commands'
      shell: bash
      run: |
        az acr login -n ${{ inputs.azure-base-url }}

    ##
    #
    # Use ssdk's maven docker-image profile to push image to ACR
    #
    ##
    - name: Build and publish docker image ACR
      shell: bash
      run: |
        if [[ "${{inputs.azureEnabled}}" == "true" ]]; then
          echo "ACR Docker build with tag ${{ steps.build-version.outputs.build-version }}"
          mvn clean package -Pdocker-image -Pno-scs -Dmaven.test.skip -Ddocker.repo.url=${{ inputs.azure-base-url }} -Djib.to.tags=${{ steps.build-version.outputs.build-version }} -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
        fi
