apiVersion: v1
kind: Service
metadata:
  name: {{ include "greenmail.fullname" . }}
  labels:
    {{- include "greenmail.labels" . | nindent 4 }}
spec:
  type: {{ .Values.greenmail.service.type }}
  ports:
    - port: {{ .Values.greenmail.service.port.smtp }}
      targetPort: smtp
      protocol: TCP
      name: smtp
    - port: {{ .Values.greenmail.service.port.smtps }}
      targetPort: smtps
      protocol: TCP
      name: smtps
    - port: {{ .Values.greenmail.service.port.imap }}
      targetPort: imap
      protocol: TCP
      name: imap
    - port: {{ .Values.greenmail.service.port.imaps }}
      targetPort: imaps
      protocol: TCP
      name: imaps
    - port: {{ .Values.greenmail.service.port.pop3 }}
      targetPort: pop3
      protocol: TCP
      name: pop3
    - port: {{ .Values.greenmail.service.port.pop3s }}
      targetPort: pop3s
      protocol: TCP
      name: pop3s
    - port: {{ .Values.greenmail.service.port.http }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "greenmail.selectorLabels" . | nindent 4 }}