name: Base/initial commit

###
# This workflow is intended to run on repo cloning/templating
# Baseline the service version in pom.xml and push to ECR
###

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - closed
jobs:
  compile:
    runs-on: ubuntu-latest
    if: |
      ( github.event_name == 'push' && github.event.base_ref == null && github.event.before == '0000000000000000000000000000000000000000' )
            || ( github.event_name == 'pull_request' &&  startsWith( github.event.pull_request.head.ref, 'feature/' ) && github.event.pull_request.number == '1' )
    strategy:
      matrix:
        java: [11]
    name: Build project with Java ${{ matrix.java }}
    timeout-minutes: 30
    env:
      DEVOPS_CICD_ECR_BASE_URL: ${{ secrets.DEVOPS_CICD_ECR_BASE_URL }}
      DEVOPS_CICD_ACR_BASE_URL: ${{ secrets.DEVOPS_CICD_ACR_BASE_URL }}

    steps:
      - name: Generate token
        id: generate_token
        uses: navikt/github-app-token-generator@v1
        with:
          private-key: ${{ secrets.GIT_GITHUB_APP_PEM_FILE }}
          app-id: ${{ secrets.GIT_GITHUB_APP_ID }}

      - uses: actions/checkout@v2
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - name: Setup Cache and Maven
        uses: ./.github/actions/setup-cache-and-maven
        with:
          mavenUsername: ${{ secrets.BAAS_BB_ARTIFACTORY_MAVEN_USERNAME }}
          mavenPassword: ${{ secrets.BAAS_BB_ARTIFACTORY_MAVEN_PASSWORD }}
          githubPackagesUser: botuser
          githubPackagesPassword: ${{ secrets.BB_GITHUB_PACKAGES_PAT }}

      - name: Create feature branch for master
        uses: ./.github/actions/create-branch
        with:
          token: ${{ steps.generate_token.outputs.token }}
          baseBranch: master
          newBranch: 'update-master/0.1.0'
          newBranchVersion: '0.1.0'

      - name: Overwrite CHANGELOG.md
        uses: ./.github/actions/changelog

      - name: Create Pull Request
        uses: thomaseizinger/create-pull-request@master
        with:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          head: 'update-master/0.1.0'
          base: master
          title: "Initialising master to 0.1.0"
          body: 'This is your First PR to master or initial commit from baas devops for new repository, once this PR is merged image will be build with version 0.1.0 and pushed to ECR'

      - name: delete-head-branch
        uses: ./.github/actions/delete-head-branch
