name: Build master

on:
  pull_request:
    branches:
      - master
    types:
      - closed
jobs:
  update-master:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'update-master/')
    strategy:
      matrix:
        java: [11]
    name: Build project with Java ${{ matrix.java }}
    timeout-minutes: 30
    outputs:
      develop-exist: ${{ steps.check-develop-branch.outputs.exist }}
    env:
      DEVOPS_CICD_ECR_BASE_URL: ${{ secrets.DEVOPS_CICD_ECR_BASE_URL }}
      DEVOPS_CICD_ACR_BASE_URL: ${{ secrets.DEVOPS_CICD_ACR_BASE_URL }}

    steps:
      - name: Generate token
        id: generate_token
        uses: navikt/github-app-token-generator@v1
        with:
          private-key: ${{ secrets.GIT_GITHUB_APP_PEM_FILE }}
          app-id: ${{ secrets.GIT_GITHUB_APP_ID }}

      - uses: actions/checkout@v2
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - name: Setup Cache and Maven
        uses: ./.github/actions/setup-cache-and-maven
        with:
          mavenUsername: ${{ secrets.BAAS_BB_ARTIFACTORY_MAVEN_USERNAME }}
          mavenPassword: ${{ secrets.BAAS_BB_ARTIFACTORY_MAVEN_PASSWORD }}
          githubPackagesUser: botuser
          githubPackagesPassword: ${{ secrets.BB_GITHUB_PACKAGES_PAT }}

      - name: build and publish artifact
        uses: ./.github/actions/build-and-publish
        with:
          token: ${{ steps.generate_token.outputs.token }}
          accessKey: ${{ secrets.DEVOPS_CICD_AWS_ACCESS_KEY_ID }}
          secretAccessKey: ${{ secrets.DEVOPS_CICD_AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.DEVOPS_CICD_AWS_REGION }}
          azure-creds: ${{ secrets.DEVOPS_CICD_NPA_AZURE_CREDENTIALS }}
          azure-base-url: ${{ secrets.DEVOPS_CICD_ACR_BASE_URL }}
          awsEnabled: ${{ secrets.AWS_ENABLED }}
          azureEnabled: ${{ secrets.AZURE_ENABLED }}
          enableBuildTagging: 'true'

      - name: delete-head-branch
        uses: ./.github/actions/delete-head-branch

      - name: Check if develop branch already exist
        id: check-develop-branch
        run: |
          existed_in_remote=$(git ls-remote --heads origin develop)
          echo $existed_in_remote
          if [[ -z ${existed_in_remote} ]]; then
              echo ::set-output name=exist::`echo false`
          else
              echo ::set-output name=exist::`echo true`
          fi

  initialise-develop:
    runs-on: ubuntu-latest
    needs: update-master
    if: ${{ needs.update-master.outputs.develop-exist == 'false' }}
    strategy:
      matrix:
        java: [ 11 ]
    name: Initialise develop branch if not exist
    timeout-minutes: 30
    env:
      DEVOPS_CICD_ECR_BASE_URL: ${{ secrets.DEVOPS_CICD_ECR_BASE_URL }}
      DEVOPS_CICD_ACR_BASE_URL: ${{ secrets.DEVOPS_CICD_ACR_BASE_URL }}

    steps:
      - name: Generate token
        id: generate_token
        uses: navikt/github-app-token-generator@v1
        with:
          private-key: ${{ secrets.GIT_GITHUB_APP_PEM_FILE }}
          app-id: ${{ secrets.GIT_GITHUB_APP_ID }}

      - name: Checkout develop
        uses: actions/checkout@v2
        with:
          ref: master
          token: ${{ steps.generate_token.outputs.token }}

      - name: Setup Cache and Maven
        uses: ./.github/actions/setup-cache-and-maven
        with:
          mavenUsername: ${{ secrets.BAAS_BB_ARTIFACTORY_MAVEN_USERNAME }}
          mavenPassword: ${{ secrets.BAAS_BB_ARTIFACTORY_MAVEN_PASSWORD }}
          githubPackagesUser: botuser
          githubPackagesPassword: ${{ secrets.BB_GITHUB_PACKAGES_PAT }}

      - name: Create develop branch
        uses: ./.github/actions/create-branch
        with:
          token: ${{ steps.generate_token.outputs.token }}
          baseBranch: master
          newBranch: develop

      - name: Extract metadata from develop version
        id: develop-version
        uses: ./.github/actions/extract-version
        with:
           branch: 'develop'
           token: ${{ steps.generate_token.outputs.token }}

      - name: Create intermediate branch
        uses: ./.github/actions/create-branch
        with:
          token: ${{ steps.generate_token.outputs.token }}
          baseBranch: develop
          newBranch: feature/${{ steps.develop-version.outputs.develop-release-version }}-${{ steps.develop-version.outputs.develop-metadata-version }}
          newBranchVersion: ${{ steps.develop-version.outputs.develop-release-version }}-${{ steps.develop-version.outputs.develop-metadata-version }}

      - name: Create Pull Request - merge release/hotfix changes into develop
        uses: thomaseizinger/create-pull-request@master
        with:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          head: feature/${{ steps.develop-version.outputs.develop-release-version }}-${{ steps.develop-version.outputs.develop-metadata-version }}
          base: develop
          title: 'Initialising develop branch to ${{ steps.develop-version.outputs.develop-release-version }}-${{ steps.develop-version.outputs.develop-metadata-version }}'
          body: ''
          reviewers:  ${{ join(github.event.pull_request.requested_reviewers.*.login, ',') }}