name: Build develop

on:
  pull_request:
    branches:
      - develop
    types:
      - closed
jobs:
  compile:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && (startsWith(github.event.pull_request.head.ref, 'feature/') || startsWith(github.event.pull_request.head.ref, 'bugfix/') || startsWith(github.event.pull_request.head.ref, 'post-release/'))
    strategy:
      matrix:
        java: [11]
    name: Build project with Java ${{ matrix.java }}
    timeout-minutes: 30
    env:
      DEVOPS_CICD_ECR_BASE_URL: ${{ secrets.DEVOPS_CICD_ECR_BASE_URL }}
      DEVOPS_CICD_ACR_BASE_URL: ${{ secrets.DEVOPS_CICD_ACR_BASE_URL }}

    steps:
      - name: Generate token
        id: generate_token
        uses: navikt/github-app-token-generator@v1
        with:
          private-key: ${{ secrets.GIT_GITHUB_APP_PEM_FILE }}
          app-id: ${{ secrets.GIT_GITHUB_APP_ID }}

      - uses: actions/checkout@v2
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - name: Setup Cache and Maven
        uses: ./.github/actions/setup-cache-and-maven
        with:
          mavenUsername: ${{ secrets.BAAS_BB_ARTIFACTORY_MAVEN_USERNAME }}
          mavenPassword: ${{ secrets.BAAS_BB_ARTIFACTORY_MAVEN_PASSWORD }}
          githubPackagesUser: botuser
          githubPackagesPassword: ${{ secrets.BB_GITHUB_PACKAGES_PAT }}

      - name: build and publish artifact
        uses: ./.github/actions/build-and-publish
        with:
          token: ${{ steps.generate_token.outputs.token }}
          accessKey: ${{ secrets.DEVOPS_CICD_AWS_ACCESS_KEY_ID }}
          secretAccessKey: ${{ secrets.DEVOPS_CICD_AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.DEVOPS_CICD_AWS_REGION }}
          azure-creds: ${{ secrets.DEVOPS_CICD_NPA_AZURE_CREDENTIALS }}
          azure-base-url: ${{ secrets.DEVOPS_CICD_ACR_BASE_URL }}
          awsEnabled: ${{ secrets.AWS_ENABLED }}
          azureEnabled: ${{ secrets.AZURE_ENABLED }}

      - name: delete-head-branch
        uses: ./.github/actions/delete-head-branch