name: Release and Hotfix Finish

###
#
# Finishes Git flow for release and hotfixes
#
# Trigger: code merged into master branch
#
###

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && (startsWith(github.event.pull_request.head.ref, 'release/') || startsWith(github.event.pull_request.head.ref, 'hotfix/'))
    strategy:
      matrix:
        java: [ 11 ]
    name: Finish the release
    timeout-minutes: 30
    outputs:
      release-version: ${{ steps.bump-version.outputs.release-version }}
    env:
      DEVOPS_CICD_ECR_BASE_URL: ${{ secrets.DEVOPS_CICD_ECR_BASE_URL }}
      DEVOPS_CICD_ACR_BASE_URL: ${{ secrets.DEVOPS_CICD_ACR_BASE_URL }}

      LABELS: ${{ join(github.event.pull_request.labels.*.name, ',') }}
    # Set flow type
    steps:
      - name: Generate token
        id: generate_token
        uses: navikt/github-app-token-generator@v1
        with:
          private-key: ${{ secrets.GIT_GITHUB_APP_PEM_FILE }}
          app-id: ${{ secrets.GIT_GITHUB_APP_ID }}

      - id: flow-type
        shell: bash
        run: |
          echo ::set-output name=release::${{ startsWith(github.event.pull_request.head.ref, 'release/') }}
          echo ::set-output name=hotfix::${{ startsWith(github.event.pull_request.head.ref, 'hotfix/') }}

      - uses: actions/checkout@v2
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - name: Setup Cache and Maven
        uses: ./.github/actions/setup-cache-and-maven
        with:
          mavenUsername: ${{ secrets.BAAS_BB_ARTIFACTORY_MAVEN_USERNAME }}
          mavenPassword: ${{ secrets.BAAS_BB_ARTIFACTORY_MAVEN_PASSWORD }}
          githubPackagesUser: botuser
          githubPackagesPassword: ${{ secrets.BB_GITHUB_PACKAGES_PAT }}

      - name: Create intermediate branch
        uses: ./.github/actions/create-branch
        with:
          token: ${{ steps.generate_token.outputs.token }}
          baseBranch: master
          newBranch: update-master/post-release

      - name: Bump version
        id: bump-version
        uses: ./.github/actions/bump-version
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - name: Create Pull Request - merge release/hotfix changes into develop
        uses: thomaseizinger/create-pull-request@master
        with:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          head: update-master/post-release
          base: master
          title: 'Updating master to ${{ steps.bump-version.outputs.release-version }}'
          body: Release pull request ${{ github.event.pull_request.number }} was merged into master branch and now updating master version from release-candidate/hotfix to version ${{ steps.bump-version.outputs.release-version }}
          reviewers:  ${{ join(github.event.pull_request.requested_reviewers.*.login, ',') }}

      - name: delete-head-branch
        uses: ./.github/actions/delete-head-branch

  update-develop:
    runs-on: ubuntu-latest
    needs: release
    strategy:
      matrix:
        java: [ 11 ]
    name: Post-release develop version update
    timeout-minutes: 30
    env:
      DEVOPS_CICD_ECR_BASE_URL: ${{ secrets.DEVOPS_CICD_ECR_BASE_URL }}
      DEVOPS_CICD_ACR_BASE_URL: ${{ secrets.DEVOPS_CICD_ACR_BASE_URL }}

    steps:

      - name: Generate token
        id: generate_token
        uses: navikt/github-app-token-generator@v1
        with:
          private-key: ${{ secrets.GIT_GITHUB_APP_PEM_FILE }}
          app-id: ${{ secrets.GIT_GITHUB_APP_ID }}

      - name: Checkout develop
        uses: actions/checkout@v2
        with:
          ref: master
          token: ${{ steps.generate_token.outputs.token }}

      - name: Setup Cache and Maven
        uses: ./.github/actions/setup-cache-and-maven
        with:
          mavenUsername: ${{ secrets.BAAS_BB_ARTIFACTORY_MAVEN_USERNAME }}
          mavenPassword: ${{ secrets.BAAS_BB_ARTIFACTORY_MAVEN_PASSWORD }}
          githubPackagesUser: botuser
          githubPackagesPassword: ${{ secrets.BB_GITHUB_PACKAGES_PAT }}

      - name: Extract release and metadata from develop version
        id: develop-version
        uses: ./.github/actions/extract-version
        with:
          branch: 'develop'
          token: ${{ steps.generate_token.outputs.token }}

      - name: Create intermediate branch
        uses: ./.github/actions/create-branch
        with:
          token: ${{ steps.generate_token.outputs.token }}
          baseBranch: master
          newBranch: post-release/${{ needs.release.outputs.release-version }}
          newBranchVersion: ${{ needs.release.outputs.release-version }}-SNAPSHOT-0

      - name: Create Pull Request - merge release/hotfix changes into develop
        uses: thomaseizinger/create-pull-request@master
        with:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          head: post-release/${{ needs.release.outputs.release-version }}
          base: develop
          title: 'Merge release/hotfix to develop - ${{ needs.release.outputs.release-version }}-SNAPSHOT-0'
          body: Release pull request ${{ github.event.pull_request.number }} was merged into master branch and version ${{ needs.release.outputs.release-version }} was released. Please review changes to be merged to develop.
          reviewers:  ${{ join(github.event.pull_request.requested_reviewers.*.login, ',') }}