name: Base/initial commit

###
# This workflow is intended to run on repo cloning/templating
# Baseline the service version in pom.xml and push to ECR
###

on:
  push:
    branches:
      - master
jobs:
  compile:
    runs-on: ubuntu-latest
    if: (github.event.base_ref == null && github.event.before == '0000000000000000000000000000000000000000') || (startsWith(github.event.pull_request.head.ref, 'feature/') && github.event.pull_request.number == '1')
    strategy:
      matrix:
        java: [11]
    name: Build project with Java ${{ matrix.java }}
    timeout-minutes: 30
    env:
      DEVOPS_CICD_ECR_BASE_URL: ${{ secrets.DEVOPS_CICD_ECR_BASE_URL }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BB_USERNAME: ${{ secrets.BB_USERNAME }}
      BB_PASSWORD: ${{ secrets.BB_PASSWORD }}
      BB_GITHUB_PACKAGES_USER: botuser
      BB_GITHUB_PACKAGES_PAT: ${{ secrets.BB_GITHUB_PACKAGES_PAT }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            ${{ runner.os }}-

      - name: Setup java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Maven Setup settings.xml with BB credentials
        uses: whelk-io/maven-settings-xml-action@v4
        with:
          repositories: '[{ "id": "Backbase Repository", "url": "https://repo.backbase.com/repo" }, { "id": "github", "url": "https://maven.pkg.github.com/${GITHUB_REPOSITORY_OWNER}/mambu-clients" }]'
          plugin_repositories: '[{ "id": "Backbase Repository", "url": "https://repo.backbase.com/repo" }]'
          servers: '[{ "id": "Backbase Repository", "username": "${BB_USERNAME}", "password": "${BB_PASSWORD}" }, { "id": "github", "username": "${BB_GITHUB_PACKAGES_USER}", "password": "${BB_GITHUB_PACKAGES_PAT}" }]'

      - name: Set git username and email
        run: |
          git config --global user.email "bot@backbase.com"
          git config --global user.name "Github Actions BOT"

      - name: Baseline project version on master
        run: |
          mvn build-helper:parse-version versions:set -DnewVersion=0.1.0 versions:commit -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

      - name: Overwrite CHANGELOG.md
        run: |
          echo "# Changelog\n\n## [Unreleased]" > CHANGELOG.md

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEVOPS_CICD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEVOPS_CICD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.DEVOPS_CICD_AWS_REGION }}

      - name: Get AWS ECR credentials
        id: ecr-credentials
        run: |
          echo "::set-output name=username::AWS"
          echo "::set-output name=password::`aws ecr get-login-password --region ${{ secrets.DEVOPS_CICD_AWS_REGION }}`"

      - name: Build docker image
        run: mvn clean package -Pdocker-image,no-scs -Dmaven.test.skip -Djib.to.auth.username=${{ steps.ecr-credentials.outputs.username }}  -Djib.to.auth.password=${{ steps.ecr-credentials.outputs.password }} -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

      - name: Push updated version to origin/master
        run: |
          git add --all
          git commit --allow-empty -m "Version updated after first commit: 0.1.0"
          git push

      - name: Create develop branch
        run: |
          git checkout -b develop

      - name: Baseline project version on develop
        run: |
          mvn build-helper:parse-version versions:set -DnewVersion=0.1.0-0.0 versions:commit -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

      - name: Push develop branch to origin
        run: |
          git add --all
          git commit -m "Initial develop version: 0.1.0-0.0"
          git push origin develop